"""empty message

Revision ID: c7c38ef77e2c
Revises: 
Create Date: 2022-08-19 19:36:26.553030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c38ef77e2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bread_type', sa.String(60), nullable=False),
    sa.Column('bread_size', sa.String(60), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(60), nullable=False),
    sa.Column('ingredients', sa.ARRAY(sa.String(length=120)), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(60), nullable=False),
    sa.Column('bread_type', sa.String(60), nullable=False),
    sa.Column('bread_size', sa.String(60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('bread')
    op.drop_table('sales')
    op.drop_table('recipe')
    # ### end Alembic commands ###